name: Dev pipeline

on:
  push:
    branches:
    - main
  workflow_dispatcher: {}

jobs:
  build-and-push:
    runs-on: [dev, amd64]
    env:
      REPO: gitea.ceperka.net/rosti/dnsapi
      GIT_USERNAME: cx
      NAMESPACE: rosti-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Configure private module credentials
        run: |
          echo "machine gitea.ceperka.net login $GIT_USERNAME password ${{ secrets.GIT_PASSWORD }}" > ~/.netrc
          chmod 600 ~/.netrc
          go env -w GONOSUMDB=gitea.ceperka.net
          go env -w GOPRIVATE=gitea.ceperka.net

      - uses: https://github.com/marcofranssen/setup-kubectl@v1.2.1
        id: kubectl
        with:
          kubectl-version: latest

      - name: Test
        run: |
          task test

      - name: Build
        run: |
          task docs
          task image IMAGE=$REPO TAG=${{env.GITHUB_SHA}} GIT_USERNAME=$GIT_USERNAME GIT_PASSWORD="${{ secrets.GIT_PASSWORD }}"
          docker login gitea.ceperka.net -u $GIT_USERNAME -p "${{ secrets.GIT_PASSWORD }}"
          task push IMAGE=$REPO TAG=${{env.GITHUB_SHA}}

